spring.application.name=backend-usersapp
#spring.datasource.url=jdbc:mysql://IP_PUBLIC:3306/db_users_springboot
spring.datasource.url=jdbc:mysql://localhost:3306/db_users_springboot
spring.datasource.username=usersapp_user
spring.datasource.password=sasa1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=DEBUG